// Dados dos livros - AUMENTADO PARA 24 LIVROS
const books = [
    {
        id: 1,
        title: "Aventuras na Floresta Encantada",
        author: "Ana Silva",
        description: "Uma emocionante história sobre amizade e coragem na floresta mágica.",
        price: 150,
        pages: 32,
        language: "Português",
        category: "Aventura",
        type: "pdf",
        popular: true,
        promotion: false
    },
    {
        id: 2,
        title: "O Segredo dos Dinossauros",
        author: "Carlos Mendes",
        description: "Descubra os mistérios dos dinossauros nesta jornada educativa.",
        price: 250,
        pages: 48,
        language: "Português",
        category: "Educativo",
        type: "fisico",
        popular: true,
        promotion: true
    },
    {
        id: 3,
        title: "A Magia das Letras",
        author: "Maria Santos",
        description: "Aprenda o alfabeto de forma divertida e mágica.",
        price: 120,
        pages: 28,
        language: "Português",
        category: "Educativo",
        type: "pdf",
        popular: false,
        promotion: true
    },
    {
        id: 4,
        title: "Super Heróis da Escola",
        author: "João Pereira",
        description: "Histórias sobre crianças que se tornam heróis no dia a dia escolar.",
        price: 280,
        pages: 56,
        language: "Português",
        category: "Aventura",
        type: "fisico",
        popular: true,
        promotion: false
    },
    {
        id: 5,
        title: "O Pequeno Jardineiro",
        author: "Sofia Rodrigues",
        description: "Aprenda sobre plantas e natureza com este livro interativo.",
        price: 180,
        pages: 36,
        language: "Português",
        category: "Natureza",
        type: "pdf",
        popular: false,
        promotion: false
    },
    {
        id: 6,
        title: "Viagem ao Espaço",
        author: "Pedro Alves",
        description: "Uma aventura pelo sistema solar com fatos científicos interessantes.",
        price: 320,
        pages: 64,
        language: "Português",
        category: "Ciência",
        type: "fisico",
        popular: true,
        promotion: true
    },
    {
        id: 7,
        title: "Contos de Fadas Modernos",
        author: "Luísa Costa",
        description: "Clássicos contos de fadas com uma reviravolta contemporânea.",
        price: 200,
        pages: 40,
        language: "Português",
        category: "Fantasia",
        type: "pdf",
        popular: true,
        promotion: false
    },
    {
        id: 8,
        title: "Animais da Savana",
        author: "António Fernandes",
        description: "Conheça os animais da savana africana e seus habitats.",
        price: 270,
        pages: 52,
        language: "Português",
        category: "Natureza",
        type: "fisico",
        popular: false,
        promotion: true
    },
    {
        id: 9,
        title: "Mistério no Castelo",
        author: "Beatriz Lima",
        description: "Resolva enigmas em um castelo antigo cheio de segredos.",
        price: 140,
        pages: 30,
        language: "Português",
        category: "Mistério",
        type: "pdf",
        popular: true,
        promotion: false
    },
    {
        id: 10,
        title: "O Mundo Submarino",
        author: "Miguel Sousa",
        description: "Explore as profundezas do oceano e suas criaturas incríveis.",
        price: 300,
        pages: 60,
        language: "Português",
        category: "Natureza",
        type: "fisico",
        popular: true,
        promotion: false
    },
    {
        id: 11,
        title: "Aprendendo Matemática Divertida",
        author: "Isabel Martins",
        description: "Matemática básica apresentada de forma lúdica e interativa.",
        price: 160,
        pages: 34,
        language: "Português",
        category: "Educativo",
        type: "pdf",
        popular: false,
        promotion: true
    },
    {
        id: 12,
        title: "Festas ao Redor do Mundo",
        author: "Rui Cardoso",
        description: "Conheça diferentes culturas através de suas celebrações.",
        price: 290,
        pages: 58,
        language: "Português",
        category: "Cultura",
        type: "fisico",
        popular: true,
        promotion: false
    },
    // 12 livros adicionais para total de 24
    {
        id: 13,
        title: "Brincando com as Formas",
        author: "Carla Sousa",
        description: "Aprenda formas geométricas brincando com os personagens.",
        price: 135,
        pages: 26,
        language: "Português",
        category: "Educativo",
        type: "pdf",
        popular: true,
        promotion: true
    },
    {
        id: 14,
        title: "A Grande Corrida",
        author: "Mário Lopes",
        description: "Uma emocionante corrida entre animais da floresta.",
        price: 265,
        pages: 44,
        language: "Português",
        category: "Aventura",
        type: "fisico",
        popular: false,
        promotion: false
    },
    {
        id: 15,
        title: "Cores e Emoções",
        author: "Teresa Almeida",
        description: "Identifique emoções através das cores.",
        price: 145,
        pages: 28,
        language: "Português",
        category: "Educativo",
        type: "pdf",
        popular: true,
        promotion: false
    },
    {
        id: 16,
        title: "O Pequeno Chef",
        author: "Ricardo Martins",
        description: "Receitas simples e divertidas para crianças.",
        price: 310,
        pages: 68,
        language: "Português",
        category: "Culinária",
        type: "fisico",
        popular: true,
        promotion: true
    },
    {
        id: 17,
        title: "Noite Estrelada",
        author: "Filipa Costa",
        description: "Descubra as constelações e histórias do céu noturno.",
        price: 175,
        pages: 38,
        language: "Português",
        category: "Ciência",
        type: "pdf",
        popular: false,
        promotion: true
    },
    {
        id: 18,
        title: "Heróis do Dia a Dia",
        author: "Alexandre Silva",
        description: "Histórias de profissões importantes na nossa sociedade.",
        price: 295,
        pages: 62,
        language: "Português",
        category: "Educativo",
        type: "fisico",
        popular: true,
        promotion: false
    },
    {
        id: 19,
        title: "Rimas Divertidas",
        author: "Sandra Oliveira",
        description: "Poemas e rimas para desenvolver a linguagem.",
        price: 125,
        pages: 24,
        language: "Português",
        category: "Poesia",
        type: "pdf",
        popular: true,
        promotion: true
    },
    {
        id: 20,
        title: "Aventura no Deserto",
        author: "Hugo Santos",
        description: "Uma jornada pelo deserto cheia de descobertas.",
        price: 275,
        pages: 50,
        language: "Português",
        category: "Aventura",
        type: "fisico",
        popular: false,
        promotion: true
    },
    {
        id: 21,
        title: "Meu Primeiro Dicionário",
        author: "Laura Mendes",
        description: "Palavras básicas com ilustrações coloridas.",
        price: 155,
        pages: 32,
        language: "Português",
        category: "Educativo",
        type: "pdf",
        popular: true,
        promotion: false
    },
    {
        id: 22,
        title: "Música para Crianças",
        author: "André Pereira",
        description: "Introdução ao mundo da música e instrumentos.",
        price: 330,
        pages: 72,
        language: "Português",
        category: "Música",
        type: "fisico",
        popular: true,
        promotion: true
    },
    {
        id: 23,
        title: "Histórias para Dormir",
        author: "Cláudia Rodrigues",
        description: "Contos calmos para uma boa noite de sono.",
        price: 140,
        pages: 30,
        language: "Português",
        category: "Fantasia",
        type: "pdf",
        popular: true,
        promotion: false
    },
    {
        id: 24,
        title: "A Cidade dos Brinquedos",
        author: "Diogo Fernandes",
        description: "Brinquedos ganham vida em uma cidade mágica.",
        price: 285,
        pages: 54,
        language: "Português",
        category: "Fantasia",
        type: "fisico",
        popular: false,
        promotion: false
    }
];

// URLs das imagens dos livros
const bookImages = {};
for (let i = 1; i <= 24; i++) {
    bookImages[i] = `https://images.unsplash.com/photo-${1544716278 + i}?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=${80 + (i % 20)}`;
}

// Corrigir algumas imagens repetidas
bookImages[8] = 'https://images.unsplash.com/photo-1512820790803-83ca734da794?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=70';
bookImages[11] = 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=70';